"""Agent definitions for the Agentic AI Data Management system."""

from .planner import PLANNER_SYSTEM_PROMPT, PLANNER_MCP_TOOLS, PLANNER_FS_WRITE_EXTENSIONS
from .data_profile_worker import (
    DATA_PROFILE_SYSTEM_PROMPT,
    DATA_PROFILE_MCP_TOOLS,
    DATA_PROFILE_FS_WRITE_EXTENSIONS,
)
from .metadata_worker import (
    METADATA_SYSTEM_PROMPT,
    METADATA_MCP_TOOLS,
    METADATA_FS_WRITE_EXTENSIONS,
)
from .data_modeling_worker import (
    DATA_MODELING_SYSTEM_PROMPT,
    DATA_MODELING_MCP_TOOLS,
    DATA_MODELING_FS_WRITE_EXTENSIONS,
)
from .data_quality_worker import (
    DATA_QUALITY_SYSTEM_PROMPT,
    DATA_QUALITY_MCP_TOOLS,
    DATA_QUALITY_FS_WRITE_EXTENSIONS,
)
from .semantical_worker import (
    SEMANTICAL_SYSTEM_PROMPT,
    SEMANTICAL_MCP_TOOLS,
    SEMANTICAL_FS_WRITE_EXTENSIONS,
)

__all__ = [
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_MCP_TOOLS",
    "PLANNER_FS_WRITE_EXTENSIONS",
    "DATA_PROFILE_SYSTEM_PROMPT",
    "DATA_PROFILE_MCP_TOOLS",
    "DATA_PROFILE_FS_WRITE_EXTENSIONS",
    "METADATA_SYSTEM_PROMPT",
    "METADATA_MCP_TOOLS",
    "METADATA_FS_WRITE_EXTENSIONS",
    "DATA_MODELING_SYSTEM_PROMPT",
    "DATA_MODELING_MCP_TOOLS",
    "DATA_MODELING_FS_WRITE_EXTENSIONS",
    "DATA_QUALITY_SYSTEM_PROMPT",
    "DATA_QUALITY_MCP_TOOLS",
    "DATA_QUALITY_FS_WRITE_EXTENSIONS",
    "SEMANTICAL_SYSTEM_PROMPT",
    "SEMANTICAL_MCP_TOOLS",
    "SEMANTICAL_FS_WRITE_EXTENSIONS",
]
